##server config
server:
  port: @server.port@
  servlet:
    context-path:
    session:
      timeout: 1800s
      tracking-modes: cookie
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  forward-headers-strategy: framework

##spring config
spring:
  application:
    name: dooxgenerator
  profiles:
    active: base
  devtools:
    add-properties: false
    livereload:
      enabled: true
      port: 35701

##log config
logging:
  level:
    root: @logging.level.root@
    web: @logging.level.web@
  file:
    path: @logging.file.path@
  context:
    name: @logging.context.name@

## project basedir
project:
  basedir: @project.basedir@
  author: Naqichuan
